let musicDB = [
  {
    id: 0,
    name: "Goteo",
    author_name: "Duki",
    img: "Goteo.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Goteo  - Duki.mp3",
  },
  {
    id: 1,
    name: "PERRO NEGRO",
    author_name: "Bad Bunny ft. Feid",
    img: "Nadie sabe lo que va a pasar mañana.png",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Perro Negro - Bad Bunny.mp3",
  },
  {
    id: 2,
    name: "Sunflower",
    author_name: "Post Malone, Swae Lee",
    img: "Hollywood's Bleeding.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "trap",
    musicName: "Sunflower - Post Malone.mp3",
  },
  {
    id: 3,
    name: "Tal vez",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Tal Vez - Paulo Londra.mp3",
  },
  {
    id: 4,
    name: "Me Porto Bonito",
    author_name: "Bad Bunny ft. Chencho Corleone",
    img: "Un Verano Sin Ti.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Me Porto Bonito - Bad Bunny.mp3",
  },
  {
    id: 5,
    name: "Azul",
    author_name: "J Balvin",
    img: "Colores.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Azul - J Balvin.mp3",
  },
  {
    id: 6,
    name: "La Rompe Corazones",
    author_name: "Daddy Yankee ft. Ozuna",
    img: "La Rompe Corazones.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "La Rompe Corazones  - Daddy Yankee.mp3",
  },
  {
    id: 7,
    name: "Despacito",
    author_name: "Luis Fonsi ft. Daddy Yankee",
    img: "Despacito.avif",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Despacito - Luis Fonsi.mp3",
  },
  {
    id: 8,
    name: "Relación Remix",
    author_name: "Sech, Daddy Yankee, J Balvin, Rosalía, Farruko",
    img: "Relación Remix.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Relación Remix - Sech.mp3",
  },
  {
    id: 9,
    name: "Te Boté - Remix",
    author_name: "Nio García, Casper, Darell, Nicky Jam, Bad Bunny, Ozuna",
    img: "Now Or Never.webp",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Te Boté Remix - Nio Garcia.mp3",
  },
  {
    id: 10,
    name: "Nathy Peluso: Bzrp Music Sessions, Vol.36",
    author_name: "Bizarrap, NATHY PELUSO",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "BZRP Music Sessions 36.mp3",
  },
  {
    id: 11,
    name: "Circles",
    author_name: "Post Malone",
    img: "Hollywood's Bleeding.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Circles - Post Malone.mp3",
  },
  {
    id: 12,
    name: "Igual Que Un Angel",
    author_name: "Kali Uchis ft Peso Pluma",
    img: "Igual Que Un Angel.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "pop",
    musicName: "Igual que un angel - Kali Uchis.mp3",
  },
  {
    id: 13,
    name: "Vamonos a Marte",
    author_name: "Kevin Kaarl",
    img: "Hasta el fin del mundo.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "pop",
    musicName: "Vamonos a Marte - Kevin Kaarl.mp3",
  },
  {
    id: 14,
    name: "Chupon",
    author_name: "Yeri Mua, El Gudi, Jey F, Alan Dazmel, Oviña",
    img: "Chupon.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Chupon - Yeri Mua.mp3",
  },
  {
    id: 15,
    name: "Attention",
    author_name: "Charlie Puth",
    img: "Attention.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Attention - Charlie Puth.mp3",
  },
  {
    id: 16,
    name: "See You Again",
    author_name: "Charlie Puth ft Wiz Khalifa",
    img: "See you again.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "See You Again - Charlie Puth.mp3",
  },
  {
    id: 17,
    name: "Sign of the Times",
    author_name: "Harry Styles",
    img: "Harry Styles.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Sign of the Times - Harry Styles.mp3",
  },
  {
    id: 18,
    name: "Botella Tra Botella",
    author_name: "Christian Nodal, Gera MX",
    img: "Botella tras botella.jpeg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Botella Tras Botella - Christian Nodal.mp3",
  },
  {
    id: 19,
    name: "Dímelo",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Dimelo - Paulo Londra.mp3",
  },
  {
    id: 20,
    name: "Homerun (Intro)",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Homerun - Paulo Londra.mp3",
  },
  {
    id: 21,
    name: "Forever Alone",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Forever Alone - Paulo Londra.mp3",
  },
  {
    id: 22,
    name: "Nena Maldición",
    author_name: "Paulo Londra (feat. Lenny Tavárez)",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Nena Maldicion - Paulo Londra.mp3",
  },
  {
    id: 23,
    name: "No Puedo",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "No Puedo - Paulo Londra.mp3",
  },
  {
    id: 24,
    name: "Adan y Eva",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Adan y Eva - Paulo Londra.mp3",
  },
  {
    id: 25,
    name: "Party",
    author_name: "Bad Bunny, Rauw Alejandro",
    img: "Un Verano Sin Ti.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Party - Bad Bunny.mp3",
  },
  {
    id: 26,
    name: "Tití Me Pregunto",
    author_name: "Bad Bunny",
    img: "Un Verano Sin Ti.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Titi Me Pregunto - Bad Bunny.mp3",
  },
  {
    id: 27,
    name: "Callaita",
    author_name: "Paulo Londra",
    img: "Un Verano Sin Ti.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Callaita - Bad Bunny.mp3",
  },
  {
    id: 28,
    name: "MONACO",
    author_name: "Bad Bunny",
    img: "Nadie sabe lo que va a pasar mañana.png",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "MONACO - Bad Bunny.mp3",
  },
  {
    id: 29,
    name: "FINA",
    author_name: "Bad Bunny, Young Miko",
    img: "Nadie sabe lo que va a pasar mañana.png",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "FINA - Bad Bunny.mp3",
  },
  {
    id: 30,
    name: "Morado",
    author_name: "J Balvin",
    img: "Colores.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Morado - J Balvin.mp3",
  },
  {
    id: 31,
    name: "Rojo",
    author_name: "J Balvin",
    img: "Colores.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Rojo - J Balvin.mp3",
  },
  {
    id: 32,
    name: "The Way I Am",
    author_name: "Charlie Puth",
    img: "Attention.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "The Way I Am - Charlie Puth.mp3",
  },
  {
    id: 33,
    name: "Woman",
    author_name: "Harry Styles",
    img: "Harry Styles.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Woman - Harry Styles.mp3",
  },
  {
    id: 34,
    name: "She",
    author_name: "Harry Styles",
    img: "Fine Line.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "She - Harry Styles.mp3",
  },
  {
    id: 35,
    name: "Golden",
    author_name: "Harry Styles",
    img: "Fine Line.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Golden - Harry Styles.mp3",
  },
  {
    id: 36,
    name: "Lights Up",
    author_name: "Harry Styles",
    img: "Fine Line.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Lights Up - Harry Styles.mp3",
  },
  {
    id: 37,
    name: "Watermelon Sugar",
    author_name: "Harry Styles",
    img: "Fine Line.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Watermelon Sugar - Harry Styles.mp3",
  },
  {
    id: 38,
    name: "Adore You",
    author_name: "Harry Styles",
    img: "Fine Line.webp",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Adore You - Harry Styles.mp3",
  },
  {
    id: 39,
    name: "Psycho (feat. Ty Dolla $ign)",
    author_name: "Post Malone, Ty Dolla $ign",
    img: "beerbongs and bentleys.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "trap",
    musicName: "Psycho - Post Malone.mp3",
  },
  {
    id: 40,
    name: "rockstar (feat. 21 Savage)",
    author_name: "Post Malone, 21 Savage",
    img: "beerbongs and bentleys.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "trap",
    musicName: "Rockstar - Post Malone.mp3",
  },
  {
    id: 41,
    name: "Take What You Want (feat. Ozzy Osbourne & Travis Scott)",
    author_name: "Post Malone, Ozzy Osbourne, Travis Scott",
    img: "Hollywood's Bleeding.jpg",
    lang: "Ingles",
    timesPlayed: 0,
    type: "pop",
    musicName: "Take What You Want - Post Malone.mp3",
  },
  {
    id: 42,
    name: "Colapso",
    author_name: "Kevin Kaarl",
    img: "Hasta el fin del mundo.jpeg",
    lang: "Español",
    timesPlayed: 0,
    type: "pop",
    musicName: "Colapso - Kevin Kaarl.mp3",
  },
  {
    id: 43,
    name: "La Diabla",
    author_name: "Xavi",
    img: "La Diabla.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "corrido",
    musicName: "La Diabla - Xavi.mp3",
  },
  {
    id: 44,
    name: "Aleman: Bzrp Music Sessions, Vol.15",
    author_name: "Bizarrap, Aleman",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Aleman Bzrp Music Sessions Vol 15.mp3",
  },
  {
    id: 45,
    name: "Chucky73: Bzrp Music Sessions, Vol.43",
    author_name: "Bizarrap, Chucky73",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Chucky73 Bzrp Music Sessions Vol 43.mp3",
  },
  {
    id: 46,
    name: "Nicky Jam: Bzrp Music Sessions, Vol.41",
    author_name: "Bizarrap, Nicky Jam",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Nicky Jam Bzrp Music Sessions Vol 41.mp3",
  },
  {
    id: 47,
    name: "Quevedo: Bzrp Music Sessions, Vol.52",
    author_name: "Bizarrap, Quevedo",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "electronica",
    musicName: "Quevedo Bzrp Music Sessions Vol 52.mp3",
  },
  {
    id: 48,
    name: "Villano Antillano: Bzrp Music Sessions, Vol.51",
    author_name: "Bizarrap, Villano Antillano",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Villano Antillano Bzrp Music Sessions Vol 51.mp3",
  },
  {
    id: 49,
    name: "Ptazeta: Bzrp Music Sessions, Vol.45",
    author_name: "Bizarrap, Ptazeta",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Ptazeta Bzrp Music Sessions Vol 45.mp3",
  },
  {
    id: 50,
    name: "Nicki Nicole: Bzrp Music Sessions, Vol.13",
    author_name: "Bizarrap, Nicki Nicole",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Nicki Nicole Bzrp Music Sessions Vol 13.mp3",
  },
  {
    id: 51,
    name: "Cazzu: Bzrp Music Sessions, Vol.32",
    author_name: "Bizarrap, Cazzu",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Cazzu Bzrp Music Sessions Vol 32.mp3",
  },
  {
    id: 52,
    name: "Eladio Carrion: Bzrp Music Sessions, Vol.40",
    author_name: "Bizarrap, Eladio Carrion",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Eladio Carrion Bzrp Music Sessions Vol 40.mp3",
  },
  {
    id: 53,
    name: "L-Gante: Bzrp Music Sessions, Vol.38",
    author_name: "Bizarrap, L-Gante",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "cumbia",
    musicName: "LGante Bzrp Music Sessions Vol38.mp3",
  },
  {
    id: 54,
    name: "Natanael Cano: Bzrp Music Sessions, Vol.59",
    author_name: "Bizarrap, Natanael Cano",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "trap",
    musicName: "Natanael Cano Bzrp Music Sessions Vol 59.mp3",
  },
  {
    id: 55,
    name: "Tiago PZK: Bzrp Music Sessions, Vol.48",
    author_name: "Bizarrap, Tiago PZK",
    img: "Music Sessions, Vol.36.jpg",
    lang: "Español",
    timesPlayed: 0,
    type: "reggaeton",
    musicName: "Tiago PZK Bzrp Music Sessions Vol 48.mp3",
  }
];

export default musicDB;
