let musicDB = [
  {
    id: 0,
    name: "Goteo",
    author_name: "Duki",
    img: "Goteo.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "trap",
    musicName: "Goteo  - Duki.mp3",
  },
  {
    id: 1,
    name: "PERRO NEGRO",
    author_name: "Bad Bunny ft. Feid",
    img: "Nadie sabe lo que va a pasar mañana.png",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "regueton",
    musicName: "Perro Negro - Bad Bunny.mp3",
  },
  {
    id: 2,
    name: "Sunflower (Spider-Man: Into the Spider-Verse)",
    author_name: "Post Malone, Swae Lee",
    img: "Sunflower.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "trap",
    musicName: "Sunflower - Post Malone.mp3",
  },
  {
    id: 3,
    name: "Tal vez",
    author_name: "Paulo Londra",
    img: "Homerun.jpeg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "trap",
    musicName: "Tal Vez - Paulo Londra.mp3",
  },
  {
    id: 4,
    name: "Me Porto Bonito",
    author_name: "Bad Bunny ft. Chencho Corleone",
    img: "Un Verano Sin Ti.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "regueton",
    musicName: "Me Porto Bonito - Bad Bunny.mp3",
  },
  {
    id: 5,
    name: "Azul",
    author_name: "J Balvin",
    img: "Colores.jpeg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "regueton",
    musicName: "Azul - J Balvin.mp3",
  },
  {
    id: 6,
    name: "La Rompe Corazones",
    author_name: "Daddy Yankee ft. Ozuna",
    img: "La Rompe Corazones.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "regueton",
    musicName: "La Rompe Corazones  - Daddy Yankee.mp3",
  },
  {
    id: 7,
    name: "Despacito",
    author_name: "Luis Fonsi ft. Daddy Yankee",
    img: "Despacito.avif",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "regueton",
    musicName: "Despacito - Luis Fonsi.mp3",
  },
  {
    id: 8,
    name: "Relación Remix",
    author_name: "Sech, Daddy Yankee, J Balvin, Rosalía, Farruko",
    img: "Relación Remix.jpeg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "regueton",
    musicName: "Relación Remix - Sech.mp3",
  },
  {
    id: 9,
    name: "Te Boté - Remix",
    author_name: "Nio García, Casper, Darell, Nicky Jam, Bad Bunny, Ozuna",
    img: "Now Or Never.webp",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "trap",
    musicName: "Te Boté Remix - Nio Garcia.mp3",
  },
  {
    id: 10,
    name: "Nathy Peluso: Bzrp Music Sessions, Vol.36",
    author_name: "Bizarrap, NATHY PELUSO",
    img: "Music Sessions, Vol.36.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "trap",
    musicName: "BZRP Music Sessions 36.mp3",
  },
  {
    id: 11,
    name: "Circles",
    author_name: "Post Malone",
    img: "Hollywood's Bleeding.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "pop",
    musicName: "Circles - Post Malone.mp3",
  },
  {
    id: 12,
    name: "Igual Que Un Angel",
    author_name: "Kali Uchis ft Peso Pluma",
    img: "Igual Que Un Angel.jpg",
    lang: "ENGLISh",
    timesPlayed: 0,
    type: "pop",
    musicName: "Igual que un angel - Kali Uchis.mp3",
  }
];

export default musicDB;
